### ISSUE TITLE
oifake.py fails to import because of missing file newVltiHzn_obsDoors.txt

### ISSUE THREAD

**Issue by pboley** [amerand/PMOIRED#2]
The title says it all. newVltiHzn_obsDoors.txt is not present in the repository...

**Comment by amerand** [comment]
my bad! I forgot to put the file in the repository... there were other bugs preventing the installation with "setup.py", but I just checked and all is working. Let me know if you have questions or need some support for help: the documentation is still quite sketchy. The best for you is to check out the notebook example
