### ISSUE TITLE
Wrong results starting from a specific position

### ISSUE THREAD

**Issue by gmella** [amerand/PMOIRED#6]
Hello,
  I discovered, trying to loop over a bunch of files extracted from OiDB for a [technical comparison](https://github.com/JMMC-OpenDev/jmmc-python-snippets/blob/main/compare-ud-fitter-on-oidb-data.ipynb) that starting from "bad" values often converge to wrong results. 

This seems the case starting to fit a disk from diameter=0. It probably exists a way to avoid such cases and this may point to other related numerical issues ? I know that other tools sometimes add the smallest values just to avoid an exact 0, but this is all I can say ;)

I may have skipped some of your documentation...

Thank you for your tool!
--
Guillaume

**Comment by amerand** [comment]
Thank you for your comment. Indeed, starting with an initial guess of 0 for a parameter is often a bad idea because of the way the chi2 minimizer works. I am not sure there is an obvious way to fix this, but this issue should be somewhat documented. I will think how.
